### ISSUE TITLE
Issues with other sites

### ISSUE THREAD

**Issue by toaster-hash** [yours-ai/YoursAI#20]
Hello, I am a usual person of the other site.
there is a other site link in your code.
please remove the code below...

File name : src/components/modalContents/fileAddModalContent.tsx
code :
```
<div className="flex flex-col text-accentBlue underline duration-150 ">
          <a className="hover:text-accentBlueHover" href="#">
            아카라이브 AI 채팅 채널
          </a>
          <a className="hover:text-accentBlueHover" href="#">
            https://aicharactercards.com
          </a>
          <a className="hover:text-accentBlueHover" href="#">
            https://character-tavern.com/character/catalog
          </a>
          <a className="hover:text-accentBlueHover" href="#">
            https://realm.risuai.net/
          </a>
        </div>
        <span>{t("tabAction.addFileModal.content.four")}</span>
      </div>
```

thank you.

**Comment by narayo9** [comment]
Thanks for first issue!
We will remove the links to other websites and ensure that no links to websites are included in the future without mutual agreement.

https://github.com/yours-ai/YoursAI/commit/744697d344f39b25f4801baadd9aefae6e218bba
